nums=[10,9,2,5,3,7,101,18]
cnt=1
l=len(nums)
arr=[]
for i in range(1,l):
    if(nums[i-1]<nums[i]):
        cnt+=1
        i+=1
    else:
        arr.append(cnt)
        print(i)
        cnt=1
        i+=1
arr.append(cnt)
print(arr)
if(l==1):
    print("1")
elif(len(arr)>0):
    print(max(arr))
else:
    print("0")